spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:language_service_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${KEYCLOAK_DOMAIN:keycloak:8080}/realms/${KEYCLOAK_REALM:master}
          jwk-set-uri: https://${KEYCLOAK_DOMAIN:keycloak:8080}/realms/${KEYCLOAK_REALM:master}/protocol/openid-connect/certs
server:
  port: 8080
  servlet:
    context-path: /api/v1
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: language-service
logging:
  level:
    com:
      example: INFO
    org.springframework: INFO
    io.opentelemetry: INFO
  name: language-service
ai-model:
    base-url: https://api.groq.com/openai/v1
    model: llama-3.1-8b-instant